### ISSUE TITLE
Current maximum response size is 16KB

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/clone-response#24]
You need to increase `highWaterMark` for bigger responses:
- https://nodejs.org/api/stream.html#stream_constructor_new_stream_writable_options
- https://nodejs.org/api/stream.html#stream_new_stream_readable_options

**Comment by lukechilds** [comment]
Sure, what do you think is a reasonable value?

**Comment by szmarczak** [comment]
I think there should be an option for this. 100KB would be a good choice. If the response exceeds, 100KB then an error should be thrown (saying that you need to increase the buffer).

**Comment by szmarczak** [comment]
Actually the stream gets paused when the downloaded data exceeds the `highWaterMark`, and resumed when the buffered data length is less than that. So there's no need to customize `highWaterMark`.
